/*
	{
		_id: objectId			- id generated by mongo
		title: String			- title
		picture: String			- picture url
		description: String		- short description
		content: String			- content
		date: date				- publication date
		author: String			- id of author
		tags: Array				- array with ids of tags
	}
 */

Articles = new Meteor.Collection('articles');
